### ISSUE TITLE
Single Line mode display bugs

### ISSUE THREAD

**Issue by jeffcox** [el1t/statusline#4]
Command history searching in single mode reverts back to the light theme:
<img width="969" alt="screen shot 2015-11-24 at 11 30 52 am" src="https://cloud.githubusercontent.com/assets/200446/11373140/dc5fda62-929e-11e5-8597-399709ca05b4.png">
<img width="1082" alt="screen shot 2015-11-24 at 11 31 01 am" src="https://cloud.githubusercontent.com/assets/200446/11373143/de102f06-929e-11e5-94b7-b60a9570b0cd.png">

I think single mode also needs a space at the end of the left prompt, line 475, but I'm willing to attribute that to personal taste.

**Comment by jeffcox** [comment]
This can be avoided to some extent by invoking single line mode, then dark mode (previous screenshots are dark, then single), however clearing after a bad completion still fills the terminal with an off color.
<img width="1082" alt="screen shot 2015-11-24 at 11 51 48 am" src="https://cloud.githubusercontent.com/assets/200446/11373806/c66900dc-92a1-11e5-8b08-450dd7ef779d.png">

**Comment by el1t** [comment]
Issue was that background needed to be reset manually instead of `$(print $FX[none])`

**Comment by el1t** [comment]
Regarding the space: it looks nice, but with `setopt histignorespace` (avoids pushing the command to history when the first character is a space) the extra space can get confusing

**Comment by jeffcox** [comment]
Thanks for the quick fix!  I see where you're coming from, I'll give it a whirl.

**Comment by el1t** [comment]
Welcome! By the way, an easy way to add the space in manually would be to delete the end of [this line](https://github.com/el1t/statusline/blob/89c646ef0783f2d375c93842ed080a6560ea132a/prezto/prompt_statusline_setup#L479) as follows

``` zsh
RPROMPT="%{$terminfo[cuf1]%}"'$(prompt_statusline -sr)'
```
