### ISSUE TITLE
How to use bold

### ISSUE THREAD

**Issue by alessaba** [el1t/statusline#5]
i used to use bold on my classic terminal. i tried to set menlo bold but the powerline becomes a “?”. how can i make the text bold without removing the powerline?

**Comment by el1t** [comment]
I don't have a custom-patched bold font at the moment, but if your bold menlo font is powerline-patched you can use the option `-f 'powerline'`to use the original powerline glyphs. On the other hand, you could also use the non-bold font and prepend the `PROMPT` string with `%B`, although that might break some formatting.

**Comment by alessaba** [comment]
Perfect! i put -f ‘powerline’ in the zshrc file and it worked! Thanks :-) 
Now it’s much better
![powerzsh](https://cloud.githubusercontent.com/assets/2400384/12140203/3ee51592-b466-11e5-9ba2-1e7080675f74.png)
