### ISSUE TITLE
Extra spaces in single line mode when using tmux

### ISSUE THREAD

**Issue by jeffcox** [el1t/statusline#7]
OSX 10.11.4, iTerm 2.9.20160313, tmux 2.2, zsh 5.1.1 (MacPorts)

Here's a normal prompt: 
<img width="969" alt="screen shot 2016-04-25 at 2 33 39 pm" src="https://cloud.githubusercontent.com/assets/200446/14799692/ba942c40-0af2-11e6-8d2a-abbc92db3081.png">

And here's tmux:
<img width="972" alt="screen shot 2016-04-25 at 2 36 00 pm" src="https://cloud.githubusercontent.com/assets/200446/14799725/ef3c30a0-0af2-11e6-9bf6-2dd4afa4ce0a.png">

For whatever reason switching to tmux adds two spaces after the prompt.

**Comment by el1t** [comment]
Somehow moving the cursor forward twice works outside of tmux, but tmux requires moving forward and back to reset it to no offset. I've implemented a quick fix, but I'll see if I can't figure out the root of the cause.
